# ruff: noqa: I001
"""add is_active to sensors

Revision ID: 7db18f4872d0
Revises: 2ca3981c9dee
Create Date: 2026-08-19 08:11:00.066358

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '7db18f4872d0'
down_revision: str | Sequence[str] | None = '2ca3981c9dee'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
